### ISSUE TITLE
Check the `Minimum required UTxO` for different transaction types

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#1096]
**The scope** of this test is to check that the `Minimum required UTxO` remains the same from release to release for different transaction types.

**Transaction types:**
- simple spent transaction (1-to-1, 1-to-many, many-to-many)
- certificates (delegation, un-delegation, pool registration/de-registration)
- multi assets (mint, spend, destroy, multiple assets/operations in the same tx)
- scripts (time locking, ttl, etc)
- Plutus scripts 
- a mix of simple spending, multi assets, scripts, Plutus scripts in the same tx, certificates 
- try to create a transaction with the size of a full block
- try to submit a transaction with the size higher than a full block

**How to:**
- compare the `Minimum required UTxO` value returned when using `transaction build` to generate different transaction types with: 
   - the value returned by `transaction calculate-min-value` for the same tx
   - the previous values of `Minimum required UTxO` from the previous runs/releases 
- it should not be possible to submit/create UTXOs smaller than `Minimum required UTxO` (the official/golden value)

**Comment by dorin100** [comment]
more details here - https://input-output-rnd.slack.com/archives/C0384PVC85Q/p1653480311274649

**Comment by mkoura** [comment]
Minimum UTxO size is computed from tx outputs, and the only possibilities are
* UTxO with just Lovelace
* UTxO with Lovelace and single native token
* UTxO with Lovelace and multiple native tokens
* UTxO with Lovelace and datum hash
* UTxO with Lovelace, single native token and datum hash
* UTxO with Lovelace, multiple native tokens and datum hash

I propose you to find suitable existing tests, and instead of using fixed amount of Lovelace, calculate the minimum value using `calculate_min_req_utxo`. Also record the value and check that the calculated value matches (same as we do for fees).
Find just single candidate test for each scenario, as we don't want to have many failing tests in case the calculation is broken (it is broken right now).

**Comment by saratomaz** [comment]
This is blocked by: 
[cardano-node 3913](https://github.com/input-output-hk/cardano-node/issues/3913 )

**Comment by dorin100** [comment]
> This is blocked by: [cardano-node 3913](https://github.com/input-output-hk/cardano-node/issues/3913)

In Babbage, yes, but I think the test can be written in Alonzo with Alonzo transactions + node 1.34.1 and then ran on Babbage nodes and confirm the functionality. 

In the end, the scope of these tests is to check that the **Minimum required UTxO** remains the same **from release to release** for different transaction types.
