### ISSUE TITLE
full db-sync sync tests on Mainnet and Testnet 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#1112]
**Scope**:
- allow running the sync from snapshot tests after the full sync from a clean state

**Details**:
- considering that at the end of the sync from clean state we have both the fully synced node and db-sync, we would everything we need to sync db-sync also from snapshot 

**Steps**:
1. fully sync node
2. fully sync db-sync from clean state
3. if everything is ok --> write the sync test values o db
4. if everything is ok --> generate a snapshot for the selected environment
5. write the values into the db (related to the snapshot creation)
6. remove the state of db-sync
7. restore db-sync from the previously created snapshot
8. write the values into the db (related to the sync from snapshot)

**Notes**:
- ideally, the script would be parameterizable --> if a parameter is provided it will run the sync from snapshot too, if not, it will run only the sync from a clean state

**Comment by ArturWieczorek** [comment]
Scope/goal:
- [X] allow running the sync from snapshot tests after the full sync from a clean state

is completed.

We gather and send results to AWS database. Adjustments & improvements can be made in the future in regards of what else we can track. There is an option (checkbox) that determines whether only full sync from clean state should be run or the whole cycle - that will, after full sync is completed, create snapshot then restore it and finally start `cardano-db-sync` in order to check if restoration was succesfull from service POV and there are no rollbacks or errors.

GitHub Actions flow: https://github.com/input-output-hk/cardano-node-tests/actions/workflows/db_sync_full_sync.yaml
![image](https://user-images.githubusercontent.com/2938515/198262161-37aba71f-452a-4817-8664-bde0c3b7d81f.png)


![image](https://user-images.githubusercontent.com/2938515/198261744-5cc02455-a46b-4ccf-ae53-d8ef2c0682ed.png)

Artifacts we expose:

![image](https://user-images.githubusercontent.com/2938515/198261948-a783183c-4e6b-443a-9898-be20378a2041.png)
