### ISSUE TITLE
db-sync delegation/rewards

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#465]
- delegate addresses and check the delegations in db-sync
- wait for addresses to get rewards and check the rewards in db-sync
- withdraw the rewards and check the results in db-sync
- undelegate address and check the results in db-sync
- redelegate address to a different pool (in same/different epoch) and check the results in db-sync
- delete/retire pool and check the delegated address in db-sync
- 
- check the rewards received by a stake address from multiple sources - https://github.com/input-output-hk/cardano-node-tests/issues/413
  - being a pool owner
  - being a pool member (same pool)
  - being a pool member (different pool)
  - getting payments from treasury
  - getting payments from reserves
  - details: https://github.com/input-output-hk/cardano-db-sync/issues/696#issuecomment-894882580

**Comment by ArturWieczorek** [comment]
Check orphaned rewards

Currently db-sync maintains its own copy of ledger state.
One of the uses of this ledger-state is to populate the **Reward** table which contains **(addr_id, amount, epoch_no, pool_id, block_id)**
However the data retrieved from legder-state includes rewards for stake addresses that have been de-registered (which means the rewards go back to the reserves) and are hence invalid (see [issue: The rewards was distributed to non-registered stake address](https://github.com/input-output-hk/cardano-db-sync/issues/415) )

Pool profitability calculation requires the inclusion of the rewards for these invalid addresses and to solve that issue an **OrphanedReward** table was added that contains the same columns as the **Reward** table so that by consulting both tables, pool profitability can still be calculated.

**orphaned rewards** occur when a stake address earns rewards in epoch **N** but has been de-registered before the rewards can be distributed at the start of epoch **N + 2**

**orphaned_rewards** do not get paid out but get sent back to the reserves.

**Comment by dorin100** [comment]
most probable orphaned_rewards table will be removed at some point so we should not spend time on automating it for the moment;

the other above actions are good candidates to automation

**Comment by mkoura** [comment]
All the mentioned checks are already implemented and used in tests.
