### ISSUE TITLE
CIP-0032 Inline datums

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#994]
**cardano-node related PR:**
#3810

_info_
https://github.com/cardano-foundation/CIPs/tree/master/CIP-0032

**AC1** _Transaction outputs are changed so that the datum field can contain either a hash or a datum (an "inline datum")_

1. Spend a Plutus utxo which contains an inline datum
    - [x] using build
    - [x] using build-raw
2. Invoke/reference multiple datums in the same transaction
    - [x] using build
    - [x] using build-raw
3. Reference two outputs that both hold the exact same datum (TxInfo should behave correctly) **waiting for dedicated script to implement this**
      #1261
4. Submit some Datums on-chain and interrogate them using query-utxo
    - [x] using build
    - [x] using build-raw
5. Attach a datum that is not valid or well-formed script data - **Expect Failure**
    - [x] using build
    - [x] using build-raw
6. Try to break CLI displaying large attached datum (try multiple utxos with large or deeply nested JSON) - **PBT**
    - [x] using build
    - [x] using build-raw

**AC2** _The min UTXO value for an output with an inline datum depends on the size of the datum, following the coinsPerUTxOWord protocol parameter_
- [x] Check that the min UTXO value with an inline datum follows the coinsPerUTxOWord protocol parameter.
- [x] how CLI behaves when TX size is exceeded !?

**AC3** _when output with an inline datum is spent, the spending transaction does not need to provide the datum itself_
1. Spend an utxo with an inline datum without providing the datum itself.
    - [x] using build
    - [x] using build-raw

**AC4** _Scripts with old versions cannot be spent in transactions that include inline datums, attempting to do so will be a phase 1 transaction validation failure._
1. Spend an old version script in a transaction that includes an inline datum - **Expect Failure**
    - [x] using build
    - [x] using build-raw

**AC5** _A reference input with datum requires no witness, and so it should only be visible in TxOut and not txInfoData map_
1. Build a transaction with an inline datum and no witness and check how the info about the output.
    - [x] using build 
    - [x] using build-raw
2. Build a transaction with an inline datum and the same datum in the witness set - **Expect Failure**
    - [x] using build
    - [x] using build-raw

**AC6** _Plutus script has visibility of the inline datum - Plutus script required_
1. Run a Plutus script validating that it has visibility of inline datums (and datum hash still)
   #1261

**AC7** _new CLI commands/parameters_
- [x] It shall be possible to review a inline datum using the transaction view command

**Comment by james-iohk** [comment]
We should also have a test that runs a plutus script validating that it has visbility of inline datums, see [tx output datum](https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/Plutus/V2/Ledger/Tx.hs#L84)

**Comment by saratomaz** [comment]
**AC1** _Transaction outputs are changed so that the datum field can contain either a hash or a datum (an "inline datum")_
- [ ] Spend a Plutus utxo which contains an inline datum
- [ ]  Invoke/reference multiple datums in the same transaction
- [ ]  Reference two outputs with the same datum
- [ ]  Submit some Datums on-chain and interrogate them using different addresses
- [ ] Reference two outputs that both hold the exact same datum (TxInfo should behave correctly)
- [ ] Attach a datum that is not valid or well-formed script data - **Expect Failure**
- [ ] Try to break CLI displaying large attached datum (try multiple utxos with large or deeply nested json) - **PBT**

**AC2** _The min UTXO value for an output with an inline datum depends on the size of the datum, following the coinsPerUTxOWord protocol parameter_
- [ ] Check that the min UTXO value with an inline datum follows the coinsPerUTxOWord protocol parameter.

**AC3** _when an output with an inline datum is spent, the spending transaction does not need to provide the datum itself_
- [ ] Spend an utxo with an inline datum without providing the datum itself.

**AC4** _Scripts with old versions cannot be spent in transactions that include inline datums, attempting to do so will be a phase 1 transaction validation failure._
- [ ] Spend an old version script in a transaction that include a inline datum - **Expect Failure**

**AC5** _A reference input with datum requires no witness, and so it should only be visible in TxOut and not txInfoData map_
- [ ] Build a transaction with an inline datum and no witness and check how the info about the output.
- [ ] Build a transaction with an inline datum and the same datum in the witness set - **Expect Failure**

**Comment by vfrsilva** [comment]
@dorin100 let's check please:
- how CLI behaves when TX size is exceeded
- I understand we are still testing for the "hash" version of the datum right? It will still be available
- Check cost to store datum is correct - what is reported by CLI and the actual deposit/fee

**Comment by vfrsilva** [comment]
@dorin100 can we add: It shall be possible to review a inline datum using the transaction view command - please
