### ISSUE TITLE
CIP-33 Reference Scripts

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#995]
**cardano-node related PR:**
[#3810](https://github.com/input-output-hk/cardano-node/pull/3810)

_info_
https://github.com/cardano-foundation/CIPs/tree/master/CIP-0033
https://github.com/input-output-hk/cardano-node/issues/3766#issuecomment-1103960050

**AC1** _Possible to reference a script_
1. Spend a Plutus utxo which contains a reference script
    - [x] using build
    - [x] using build-raw
2. Invoke/reference multiple scripts in the same transaction
    - [x] using build
    - [x] using build-raw
3. Mix of attached and reference scripts in a single valid transaction
    - [x] using build
    - [x] using build-raw
4. Use both the reference script and datum at the same utxo input
    - [x] using build
    - [x] using build-raw
5. Reference the same output with the same script multiple times in a single transaction
    - [x] using build
    - [x] using build-raw
6. Reference several instances of the same script at different outputs in a single transaction
    - [x] using build
    - [x] using build-raw
7. Use a reference script in order to authorize a Plutus locked delegation cert/minting policy/withdrawal **check cardano-node PR #4034**
    - [x] using build
    - [x] using build-raw
8. Reference something that is not a script (or script that is not well-formed) - **Expect failure**
    - [x] using build
    - [x] using build-raw
9. Reference one valid script and one invalid - **Expect failure**
    - [x] using build
    - [x] using build-raw

**AC2** _Fee and collateral are cheaper when using a reference script_
1. Submit a transaction with an attached script, submit an equal transaction with the script referenced, and compare the fees and collaterals.
    - [x] using build
    - [x] using build-raw
2. check that the cost for a transaction with reference scripts is respecting the cost model
    - [x] using build
    - [x] using build-raw
3. check that the cost for a transaction with reference scripts, referenced datums, referenced inputs and collaterals is respecting the cost model
    - [x] using build
    - [x] using build-raw
4. check that consuming/spending an utxo with referenced reference scripts, referenced datums, referenced inputs will make those data not available anymore and the full ADA amount from the initial utxo is correctly transferred
    - [x] using build
    - [x] using build-raw

5. check the minAdaRequired and `execution units` for different scenarios - transactions with reference scripts, reference datums, reference inputs, Plutus, script + combinations between them:
    - [x] ADA only
    - [x] ADA + tokens
    - [x] ADA + datum
    - [x] ADA + inline datum
    - [x] ADA + tokens + datum
    - [x] ADA + tokens + inline datum
    - [x] ADA + reference script
    - [x] ADA + tokens + reference script
    - [x] ADA + datum + reference script
    - [x] ADA + inline datum + reference script
    - [x] ADA + tokens + datum + reference script
    - [x] ADA + tokens + inline datum + reference script

- [x] check `execution units` for different scenarios - transactions with reference scripts, reference datums, reference inputs, Plutus, script + combinations between them

**AC3** Scripts with old versions cannot use reference scripts, attempting to do so will be a phase 1 transaction validation failure.
1. spend an old version script in a transaction that includes a reference script - **Expect Failure**
    - [x] using build
    - [x] using build-raw
2. spend an utxo in the same transaction with a Plutus V1 / V2 reference script (referencing a script should not have any effect on spending an unrelated utxo)
    - [x] using build 
    - [x] using build-raw

>  try attaching and referencing the same script in a single valid transaction. Should run validation twice for each input? Check that txOutReferenceScript is correct.
>  a tx with a Plutus script which is both needed and supplied in two ways: 1) via reference script, 2) in the script witnesses

- [x] **AC4** `memUnits` and `cpuUnits` 

**AC5** run a Plutus script validating that the correct script hash is attached to the input
   #1261

**AC7** simple scripts
- [x]  reference simple (not Plutus) scripts

**Comment by james-iohk** [comment]
We should also have a test that runs a plutus script to validate that the correct script hash is attached to input, see https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/Plutus/V2/Ledger/Tx.hs#L85

**Comment by saratomaz** [comment]
**cardano-node related PR:**
#3810

_info_
https://github.com/cardano-foundation/CIPs/tree/master/CIP-0033
https://github.com/input-output-hk/cardano-node/issues/3766#issuecomment-1103960050

**AC1** _Possible to reference a script_
- [ ] Spend a Plutus utxo which contains a reference script
- [ ] Invoke/reference multiple scripts in the same transaction
- [ ] Use both the reference script and datum at the same utxo input
- [ ] Reference the same output with the same script multiple times in a single transaction
- [ ] Reference several instances of the same script at different outputs in a single transaction
- [ ] Use a reference script in order to authorize a Plutus locked delegation cert/minting policy/withdrawal
- [ ] Reference something that is not a script (or script that is not well-formed) - **Expect failure**
- [ ] Reference one valid script and one invalid - **Expect failure**

**AC2** _Fee and collateral are cheaper when using a reference script_
- [ ] Submit a transaction with a attached script, submit the same transaction with the script referenced, compare the fees and collaterals.

**AC3** Scripts with old versions cannot use reference scripts, attempting to do so will be a phase 1 transaction validation failure.
- [ ] Spend an old version script in a transaction that include a reference script - **Expect Failure**



 a tx with a Plutus script which is both needed and supplied in two ways: 1) via reference script, 2) in the script witnesses

**Comment by vfrsilva** [comment]
@dorin100 I see we can still test the following:

1. When UTxO has enough to store the script
2. When UTxO doesn't have enough to store the script
a. Error message OK?
3. When Script size is bigger than TX size
a. Error message OK?
4. When the script is invalid
a. Error message OK?
5. Test if the real cost to store the script is the same that CLI reports
